Adding documentation with a srs file
ljte/lab-project pull request #2
Opened 2020-09-26 19:57 UTC by ljte

2020-09-29 09:04 UTC, inauros requested changes
**README.md**
Please add the following sections:
1. application functions (for example: adding / updating / removing departments, displaying a list of employees, etc.)
2. installation (in the future, this section will be filled with instructions for installing / configuring / running the application locally)

2020-09-29 14:05 UTC, inauros requested changes

2020-09-29 14:05 UTC, inauros commented on documentation/Specification.md
> +-   Filtering departments by the average salary;
Please add the following functions:
1. search by user name
2. search by department name
3. filter users by department name

2020-09-29 14:05 UTC, inauros commented on documentation/Specification.md
> +Pic 1.1 view of the Department list
Please replace "New department: Add" with just one button "New Department".

2020-09-29 14:05 UTC, inauros commented on documentation/Specification.md
> +
Please add an ability to search by department name

2020-09-29 14:05 UTC, inauros commented on documentation/Specification.md
> +-   If any data is entered incorrectly, incorrect data message is displayed;
Please add a mockup for this use case

2020-09-29 14:05 UTC, inauros commented on documentation/Specification.md
> +-   If an error occurs, then the error message is displayed;
Please add a mockup for this use case

2020-09-29 14:05 UTC, inauros commented on documentation/Specification.md
> +-   If any data is entered incorrectly, the incorrect data message is displayed;
Please add a mockup for this use case

2020-09-29 14:05 UTC, inauros commented on documentation/Specification.md
> +-   If error occurs, the error message is displayed;
Please add a mockup for this use case

2020-09-29 14:05 UTC, inauros commented on documentation/Specification.md
> +-   The recorded is deleted from the database;
Please replace "recorded" with "record" :)

2020-09-29 14:05 UTC, inauros commented on documentation/Specification.md
> +-   If error occurs, the error message is displayed;
Please add a mockup for this use case

2020-09-29 14:05 UTC, inauros commented on documentation/Specification.md
> +-   The Departments page is displayed without any changes;
Please add scenarios and mockups for the Employees page.

2020-09-29 14:05 UTC, inauros commented on documentation/Specification.md
> +
What is the expected behavior if a user tries to delete a department when that department has at least one employee?

2020-09-29 14:15 UTC, ljte commented on documentation/Specification.md
> +-   The Departments page is displayed without any changes;
Done

2020-09-29 14:49 UTC, ljte commented on documentation/Specification.md
> +-   Filtering departments by the average salary;
Done

2020-09-29 14:49 UTC, ljte commented on documentation/Specification.md
> +Pic 1.1 view of the Department list
Done

2020-09-29 14:50 UTC, ljte commented on documentation/Specification.md
> +-   The recorded is deleted from the database;
Done

2020-09-29 15:16 UTC, ljte commented on documentation/Specification.md
> +
Done

2020-09-29 15:21 UTC, ljte commented on documentation/Specification.md
> +-   If any data is entered incorrectly, incorrect data message is displayed;
Done

2020-09-29 15:21 UTC, ljte commented on documentation/Specification.md
> +-   If an error occurs, then the error message is displayed;
Done

2020-09-29 15:21 UTC, ljte commented on documentation/Specification.md
> +-   If any data is entered incorrectly, the incorrect data message is displayed;
Done

2020-09-29 15:25 UTC, ljte commented on documentation/Specification.md
> +-   If error occurs, the error message is displayed;
Done

2020-09-29 15:25 UTC, ljte commented on documentation/Specification.md
> +-   If error occurs, the error message is displayed;
Done

2020-09-29 15:39 UTC, ljte commented on documentation/Specification.md
> +
Done

2020-10-01 05:51 UTC, inauros approved these changes

2020-10-01 13:54 UTC, merged